
import { createClient } from '@supabase/supabase-js';
import { Message } from '../types';

// Credentials injected for instant deployment
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL || "https://ivvglvpnryiwjdqdsvka.supabase.co";
const supabaseAnonKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dmdsdnBucnlpd2pkcWRzdmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMTcxMzEsImV4cCI6MjA4MDY5MzEzMX0.RgQVnTVjptaZTArvv8OvdWxqc7rgnaQaoOhuZH4GtsA";

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials missing! Chat will not work.");
}

export const supabase = createClient(
  supabaseUrl,
  supabaseAnonKey,
  {
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

/* 
  --- SQL FOR CHAT HISTORY (OPTIONAL) ---
  Run this in Supabase SQL Editor to enable history:

  create table if not exists chat_history (
    id bigint generated by default as identity primary key,
    user_id text not null,
    content text,
    type text not null,
    sender text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  alter table chat_history disable row level security;
*/

export const saveMessageToHistory = async (userId: string, message: Message) => {
  // Only save text messages for history to save bandwidth/storage
  if (message.type !== 'text') return;

  const { error } = await supabase.from('chat_history').insert({
    user_id: userId,
    content: message.text,
    type: message.type,
    sender: message.sender,
    created_at: new Date(message.timestamp).toISOString()
  });

  if (error) console.error("Failed to save history:", error);
};

export const fetchChatHistory = async (userId: string): Promise<Message[]> => {
  const { data, error } = await supabase
    .from('chat_history')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: true })
    .limit(50);

  if (error || !data) return [];

  return data.map((row: any) => ({
    id: row.id.toString(),
    text: row.content,
    type: row.type as 'text',
    sender: row.sender as 'me' | 'stranger' | 'system',
    timestamp: new Date(row.created_at).getTime()
  }));
};
